### ISSUE TITLE
`args.weight_decay` is missed

### ISSUE THREAD

**Issue by ideafang** [dingyuan-shi/Graph-Diffusion-Planning#1]
Dear Dingyuan,

Thanks for your interesting research! But the code seems miss the `args.weight_decay` hyper parameter setting which is used in `main.py` line 54 and line 70.

Hope to your help, thanks!

Henry

**Comment by dingyuan-shi** [comment]
We are sorry for the mistake, the commit f41d1f40d665fcb8d136159469c5a900d6ef097c will solve this issue
