### ISSUE TITLE
About NLL

### ISSUE THREAD

**Issue by dixinyinli2** [dingyuan-shi/Graph-Diffusion-Planning#4]
In the function `eval_nll`, I am confused about `self.max_T // 20`, why choose to divide by 20. Thank you very much for your answer!

```
def eval_nll(self, real_paths):
        total = len(real_paths)
        nlls = np.zeros(total)
        batch_traj_num = 200
        n_batch = (total + batch_traj_num - 1) // batch_traj_num
        
        for k in range(n_batch):
            left = k * batch_traj_num
            right = min((k + 1) * batch_traj_num, total)
            batch_size = right - left
            xs = [torch.tensor(path).to(self.device) for path in real_paths[left: right]]
            lengths = [x.shape[0] for x in xs]
            ts = torch.tensor([self.max_T // 20]).repeat(batch_size).to(self.device)
            x_t = self.destroyer.diffusion(xs, ts)
            xt_padded = pad_sequence(x_t, batch_first=True, padding_value=0).long()
            lengths = torch.Tensor(lengths).long().to(self.device)
            _, probs = self.sample_with_len(lengths, ret_distr=True, xt=xt_padded, T=self.max_T // 20)
            for i, path in enumerate(real_paths[left: right]):
                logits = torch.masked_fill(probs_to_logits(probs[i])[1:lengths[i], :], self.A[path[:-1]] == 0, -1e20)
                prob = torch.softmax(logits, dim=-1)
                nlls[i + left] -= (prob[0, path[0]] + 0.001).log()
                nlls[i + left] -= (prob[torch.arange(lengths[i] - 1), path[1:]] + 0.00001).log().sum()
        return nlls
```

**Comment by dingyuan-shi** [comment]
It makes no sense to evaluate NLL if we set to self.max_T. If we set timestep to max_T, the xT will nearly be pure noise, and the path we denoised is very much alike sampling a new path which is irrelevant to the original x0.
If we set a relative small T', then the xT will not far from x0, so the denoise process will be capable of getting the original x0.

**Comment by dixinyinli2** [comment]
I got you，thanks a lot！

---- Replied Message ----
| From | Dingyuan ***@***.***> |
| Date | 06/21/2024 23:15 |
| To | dingyuan-shi/Graph-Diffusion-Planning ***@***.***> |
| Cc | dixinyinli2 ***@***.***>,
Author ***@***.***> |
| Subject | Re: [dingyuan-shi/Graph-Diffusion-Planning] About NLL (Issue #4) |

It makes no sense to evaluate NLL if we set to self.max_T. If we set timestep to max_T, the xT will nearly be pure noise, and the path we denoised is very much alike sampling a new path which is irrelevant to the original x0.
If we set a relative small T', then the xT will not far from x0, so the denoise process will be capable of getting the original x0.
